const actions = {
  SET_STATE: 'song/SET_STATE',
  GET_SONGS: 'song/GET_SONGS',
  GET_LATEST_SONGS: 'song/GET_LATEST_SONGS',
  GET_HOT_SONGS: 'song/GET_HOT_SONGS',
  GET_SONG_BY_ID: 'song/GET_SONG_BY_ID',
  GET_SONGS_BY_GENRE: 'song/GET_SONGS_BY_GENRE',
  GET_SAME_GENRE_SONGS: 'song/GET_SAME_GENRE_SONGS',
  GET_SAME_SINGER_SONGS: 'song/GET_SAME_SINGER_SONGS',
}

export default actions
